module.exports = Object.freeze({

  // Validation-level codes
  INVALID_INPUT_MODEL: 1,
  REQUIRED_FIELD_EXPECTED: 2,
  NO_RECORDS_FOUND: 3,
  CANNOT_BE_NEGATIVE: 4,
  CANNOT_BE_EQUAL: 5,

  // Error-level codes
  GENERIC_ERROR_MESSAGE: 500,
  FAILED_TO_SEND_SIGNED_TRANSACTION: 511,
  FAILED_TO_ESTIMATE_GAS: 512,
  FAILED_TO_GET_NONCE: 513,
  FAILED_TO_GET_GAS_PRICE: 514,
  FAILED_TO_GET_LATEST_TX_BLOCK: 515,
  FAILED_TO_EXECUTE_CONTRACT: 516
})
